encoding:
  reed_solomon:
    nsize: 255                       # Total block size (default: 255 for GF(2^8))
    nsym: 32                         # Number of error correction symbols (ECC)
    fcr: 0                           # First consecutive root
    prim: 0x11d                      # Primitive polynomial
    generator: 2                     # Generator element
    c_exp: 8                         # Galois Field exponent (2^c_exp)
    single_gen: True                 # Use single generator polynomial
  destination_directory: "artifacts" 
  padding_size:  1073741824           #padding size = 1 Gb
  encoded_file_suffix : ".dll"    
  metadata2:
    delimiter: b"\xDE\xAD\xBE\xEF"
    d1_gap: 0                         # 0 B
    d2_gap: 131072                    # 128 KiB
    d3_gap: 1073741824                # 1 GiB
decoding:
