encoding:
  reed_solomon:
    nsize: 255                       # Total block size (default: 255 for GF(2^8))
    nsym: 32                         # Number of error correction symbols (ECC)
    fcr: 0                           # First consecutive root
    prim: 0x11d                      # Primitive polynomial
    generator: 2                     # Generator element
    c_exp: 8                         # Galois Field exponent (2^c_exp)
    single_gen: True                 # Use single generator polynomial
  destination_directory: "artifacts" 
  encoded_file_suffix : ".dll"    
  padding_size:  1073741824           #padding size = 1 Gb
  delimiter: b"\xDE\xAD\xBE\xEF"
decoding:
